pipelines:
 - name: pipeline_1
   steps:
     - name: step_1
       type: Bash
       configuration:
         inputResources:
           - name: "myAppRepoallok1"
           - name: "myAppRepoallok3"
       execution:
         onExecute:
           - echo $MY_MESSAGE
